arch = { packages = [
  # Browsers
  "zen-browser-bin",

  # Utilities
  "bitwarden",
  "ferdium-bin",
  "obsidian",
  "kdeconnect",
  "nautilus",
  "discord",

  # CLI
  "ai-usagebar-bin",
  "bluetui",
  "calcure",
  "speedtest-cli",
  "wiremix",
  "wlctl-bin",
] }
