arch = { packages = [
  # Desktop environments
  "cosmic-session",
  "hyprland",

  # Hyprland Utils
  "hypridle",
  "hyprlock",
  "hyprpolkitagent",
  "hyprsunset",
  "hyprpicker",

  # Display server & portals
  "xdg-desktop-portal-cosmic",
  "xdg-desktop-portal-hyprland",

  # Display managers & themes
  "ly",

  # Cursors & icons
  "bibata-cursor-theme-bin",
  "kora-icon-theme",

  # Window manager utilities
  "nwg-look",
  "wev",
  "grim",
  "slurp",
  "tesseract",
  "tesseract-data-eng",
  "tesseract-data-spa",
  "imagemagick",
  "wl-screenrec-git",
  "translate-shell",
  "awww",
  "matugen",

  # UI Tool
  "rofi",
  "swayosd",
  "waybar-git",
  "waypaper",

  # Waybar Modules
  "waybar-lyric",

  # Fonts
  "noto-fonts-emoji",
  "ttf-firacode-nerd",
  "ttf-ms-fonts",
  "ttf-roboto",

  # Qt libraries
  "qt6-multimedia-ffmpeg",
  "qt6-virtualkeyboard",
  "qt5-tools",
  "qt5-websockets",
  "qt6-websockets",
] }
