# ╔═╗┬ ┬ ┬┌┬┐┌┬┐  ┌┬┐┌─┐┌┬┐┌─┐
# ╚═╗│ └┬┘ ││ ││───│││ │ │ └─┐
# ╚═╝┴─┘┴ ─┴┘─┴┘  ─┴┘└─┘ ┴ └─┘
# Starship Configuration File

format = "$os$nix_shell$username$directory$git_status$character "
continuation_prompt = "-> "
add_newline = true

[line_break]
disabled = true

[os]
style = "fg:sky"
disabled = false

[os.symbols]
Arch = " "

[directory]
truncation_length = 2
truncate_to_repo = true
format = " [$read_only]($read_only_style)[$path]($style)"
repo_root_format = " [$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)"
read_only = " "
style = "fg:blue"
read_only_style = "fg:blue"
repo_root_style = "fg:yellow"

[username]
style_root = "fg:blue"
style_user = "fg:blue"
format = " [$user]($style)"
show_always = true

[username.aliases]
root = "󰈸"

[git_status]
style = "fg:yellow"
format = " [$all_status$ahead_behind]($style)"
conflicted = "=$count "
ahead = "⇡$count "
behind = "⇣$count "
untracked = "?$count "
stashed = "\\$$count "
modified = "!$count "
staged = "+$count "
renamed = "»$count "
deleted = "✘$count "

[character]
format = " [$symbol](fg:blue)"

[nix_shell]
disabled = false
format = "[ \\($name\\)]($style)"
style = "fg:sky"
