format = "$os$nix_shell$username$directory$git_status$character "
continuation_prompt = "-> "
add_newline = true

[line_break]
disabled = true


palette = "noctalia"

[os]
style = "fg:sky"
disabled = false

[os.symbols]
Arch = " "

[directory]
truncation_length = 2
truncate_to_repo = true
format = " [$read_only]($read_only_style)[$path]($style)"
repo_root_format = " [$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)"
read_only = " "
style = "fg:blue"
read_only_style = "fg:blue"
repo_root_style = "fg:yellow"

[username]
style_root = "fg:blue"
style_user = "fg:blue"
format = " [$user]($style)"
show_always = true

[username.aliases]
root = "󰈸"

[git_status]
style = "fg:yellow"
format = " [$all_status$ahead_behind]($style)"
conflicted = "=$count "
ahead = "⇡$count "
behind = "⇣$count "
untracked = "?$count "
stashed = "\\$$count "
modified = "!$count "
staged = "+$count "
renamed = "»$count "
deleted = "✘$count "

[character]
format = " [$symbol](fg:blue)"

[nix_shell]
disabled = false
format = "[ \\($name\\)]($style)"
style = "fg:sky"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (wallpaper-based)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#b7c4ff"
red       = "#ffb4ab"
green     = "#c2c5dd"
yellow    = "#e4bad9"
cyan      = "#c2c5dd"
magenta   = "#b7c4ff"
white     = "#e4e1e6"
black     = "#131316"

# Extended palette (Catppuccin-compatible names)
rosewater = "#e4bad9"
flamingo  = "#e4bad9"
pink      = "#b7c4ff"
mauve     = "#4459a9"
maroon    = "#ffb4ab"
peach     = "#e4bad9"
teal      = "#c2c5dd"
sky       = "#c2c5dd"
sapphire  = "#c2c5dd"
lavender  = "#4459a9"

# Text shades
text      = "#e4e1e6"
subtext1  = "#c6c5d0"
subtext0  = "#90909a"

# Surface shades
overlay2  = "#90909a"
overlay1  = "#c6c5d0"
overlay0  = "#45464f"
surface2  = "#45464f"
surface1  = "#131316"
surface0  = "#131316"
base      = "#131316"
mantle    = "#131316"
crust     = "#43273f"
# <<< NOCTALIA STARSHIP PALETTE <<<
