color0 #131316
color1 #ffb4ab
color2 #b7c4ff
color3 #c2c5dd
color4 #e4bad9
color5 #b7c4ff
color6 #c2c5dd
color7 #e4e1e6
color8 #90909a
color9 #ffb4ab
color10 #b7c4ff
color11 #c2c5dd
color12 #e4bad9
color13 #b7c4ff
color14 #c2c5dd
color15 #e4e1e6

cursor                #e4e1e6
cursor_text_color     #131316
background            #131316
foreground            #e4e1e6
selection_foreground  #c6c5d0
selection_background  #45464f
active_border_color   #b7c4ff
inactive_border_color #45464f
url_color             #b7c4ff

active_tab_foreground   #0d2878
active_tab_background   #b7c4ff
inactive_tab_foreground #c6c5d0
inactive_tab_background #45464f
cursor_trail_color      #c6c5d0
