# Add theme to plymouth folder
CopyFileTo /plymouth/themes/Deadlight/progress-54.png /usr/share/plymouth/themes/Deadlight/progress-54.png
CopyFileTo /plymouth/themes/Deadlight/progress-27.png /usr/share/plymouth/themes/Deadlight/progress-27.png
CopyFileTo /plymouth/themes/Deadlight/progress-10.png /usr/share/plymouth/themes/Deadlight/progress-10.png
CopyFileTo /plymouth/themes/Deadlight/progress-5.png /usr/share/plymouth/themes/Deadlight/progress-5.png
CopyFileTo /plymouth/themes/Deadlight/progress-33.png /usr/share/plymouth/themes/Deadlight/progress-33.png
CopyFileTo /plymouth/themes/Deadlight/progress-11.png /usr/share/plymouth/themes/Deadlight/progress-11.png
CopyFileTo /plymouth/themes/Deadlight/progress-43.png /usr/share/plymouth/themes/Deadlight/progress-43.png
CopyFileTo /plymouth/themes/Deadlight/progress-31.png /usr/share/plymouth/themes/Deadlight/progress-31.png
CopyFileTo /plymouth/themes/Deadlight/progress-52.png /usr/share/plymouth/themes/Deadlight/progress-52.png
CopyFileTo /plymouth/themes/Deadlight/progress-37.png /usr/share/plymouth/themes/Deadlight/progress-37.png
CopyFileTo /plymouth/themes/Deadlight/progress-35.png /usr/share/plymouth/themes/Deadlight/progress-35.png
CopyFileTo /plymouth/themes/Deadlight/progress-56.png /usr/share/plymouth/themes/Deadlight/progress-56.png
CopyFileTo /plymouth/themes/Deadlight/progress-23.png /usr/share/plymouth/themes/Deadlight/progress-23.png
CopyFileTo /plymouth/themes/Deadlight/progress-46.png /usr/share/plymouth/themes/Deadlight/progress-46.png
CopyFileTo /plymouth/themes/Deadlight/progress-4.png /usr/share/plymouth/themes/Deadlight/progress-4.png
CopyFileTo /plymouth/themes/Deadlight/progress-13.png /usr/share/plymouth/themes/Deadlight/progress-13.png
CopyFileTo /plymouth/themes/Deadlight/progress-53.png /usr/share/plymouth/themes/Deadlight/progress-53.png
CopyFileTo /plymouth/themes/Deadlight/progress-62.png /usr/share/plymouth/themes/Deadlight/progress-62.png
CopyFileTo /plymouth/themes/Deadlight/progress-55.png /usr/share/plymouth/themes/Deadlight/progress-55.png
CopyFileTo /plymouth/themes/Deadlight/progress-59.png /usr/share/plymouth/themes/Deadlight/progress-59.png
CopyFileTo /plymouth/themes/Deadlight/progress-0.png /usr/share/plymouth/themes/Deadlight/progress-0.png
CopyFileTo /plymouth/themes/Deadlight/progress-29.png /usr/share/plymouth/themes/Deadlight/progress-29.png
CopyFileTo /plymouth/themes/Deadlight/progress-19.png /usr/share/plymouth/themes/Deadlight/progress-19.png
CopyFileTo /plymouth/themes/Deadlight/progress-7.png /usr/share/plymouth/themes/Deadlight/progress-7.png
CopyFileTo /plymouth/themes/Deadlight/progress-39.png /usr/share/plymouth/themes/Deadlight/progress-39.png
CopyFileTo /plymouth/themes/Deadlight/progress-40.png /usr/share/plymouth/themes/Deadlight/progress-40.png
CopyFileTo /plymouth/themes/Deadlight/progress-15.png /usr/share/plymouth/themes/Deadlight/progress-15.png
CopyFileTo /plymouth/themes/Deadlight/progress-8.png /usr/share/plymouth/themes/Deadlight/progress-8.png
CopyFileTo /plymouth/themes/Deadlight/progress-9.png /usr/share/plymouth/themes/Deadlight/progress-9.png
CopyFileTo /plymouth/themes/Deadlight/progress-14.png /usr/share/plymouth/themes/Deadlight/progress-14.png
CopyFileTo /plymouth/themes/Deadlight/progress-41.png /usr/share/plymouth/themes/Deadlight/progress-41.png
CopyFileTo /plymouth/themes/Deadlight/progress-49.png /usr/share/plymouth/themes/Deadlight/progress-49.png
CopyFileTo /plymouth/themes/Deadlight/progress-21.png /usr/share/plymouth/themes/Deadlight/progress-21.png
CopyFileTo /plymouth/themes/Deadlight/progress-48.png /usr/share/plymouth/themes/Deadlight/progress-48.png
CopyFileTo /plymouth/themes/Deadlight/progress-44.png /usr/share/plymouth/themes/Deadlight/progress-44.png
CopyFileTo /plymouth/themes/Deadlight/progress-24.png /usr/share/plymouth/themes/Deadlight/progress-24.png
CopyFileTo /plymouth/themes/Deadlight/progress-26.png /usr/share/plymouth/themes/Deadlight/progress-26.png
CopyFileTo /plymouth/themes/Deadlight/progress-42.png /usr/share/plymouth/themes/Deadlight/progress-42.png
CopyFileTo /plymouth/themes/Deadlight/progress-3.png /usr/share/plymouth/themes/Deadlight/progress-3.png
CopyFileTo /plymouth/themes/Deadlight/progress-38.png /usr/share/plymouth/themes/Deadlight/progress-38.png
CopyFileTo /plymouth/themes/Deadlight/progress-20.png /usr/share/plymouth/themes/Deadlight/progress-20.png
CopyFileTo /plymouth/themes/Deadlight/progress-6.png /usr/share/plymouth/themes/Deadlight/progress-6.png
CopyFileTo /plymouth/themes/Deadlight/Deadlight.script /usr/share/plymouth/themes/Deadlight/Deadlight.script
CopyFileTo /plymouth/themes/Deadlight/progress-51.png /usr/share/plymouth/themes/Deadlight/progress-51.png
CopyFileTo /plymouth/themes/Deadlight/Deadlight.plymouth /usr/share/plymouth/themes/Deadlight/Deadlight.plymouth
CopyFileTo /plymouth/themes/Deadlight/progress-50.png /usr/share/plymouth/themes/Deadlight/progress-50.png
CopyFileTo /plymouth/themes/Deadlight/progress-1.png /usr/share/plymouth/themes/Deadlight/progress-1.png
CopyFileTo /plymouth/themes/Deadlight/progress-25.png /usr/share/plymouth/themes/Deadlight/progress-25.png
CopyFileTo /plymouth/themes/Deadlight/progress-57.png /usr/share/plymouth/themes/Deadlight/progress-57.png
CopyFileTo /plymouth/themes/Deadlight/progress-36.png /usr/share/plymouth/themes/Deadlight/progress-36.png
CopyFileTo /plymouth/themes/Deadlight/progress-22.png /usr/share/plymouth/themes/Deadlight/progress-22.png
CopyFileTo /plymouth/themes/Deadlight/progress-60.png /usr/share/plymouth/themes/Deadlight/progress-60.png
CopyFileTo /plymouth/themes/Deadlight/progress-34.png /usr/share/plymouth/themes/Deadlight/progress-34.png
CopyFileTo /plymouth/themes/Deadlight/progress-32.png /usr/share/plymouth/themes/Deadlight/progress-32.png
CopyFileTo /plymouth/themes/Deadlight/progress-61.png /usr/share/plymouth/themes/Deadlight/progress-61.png
CopyFileTo /plymouth/themes/Deadlight/progress-58.png /usr/share/plymouth/themes/Deadlight/progress-58.png
CopyFileTo /plymouth/themes/Deadlight/progress-30.png /usr/share/plymouth/themes/Deadlight/progress-30.png
CopyFileTo /plymouth/themes/Deadlight/progress-18.png /usr/share/plymouth/themes/Deadlight/progress-18.png
CopyFileTo /plymouth/themes/Deadlight/progress-28.png /usr/share/plymouth/themes/Deadlight/progress-28.png
CopyFileTo /plymouth/themes/Deadlight/progress-16.png /usr/share/plymouth/themes/Deadlight/progress-16.png
CopyFileTo /plymouth/themes/Deadlight/progress-17.png /usr/share/plymouth/themes/Deadlight/progress-17.png
CopyFileTo /plymouth/themes/Deadlight/progress-12.png /usr/share/plymouth/themes/Deadlight/progress-12.png
CopyFileTo /plymouth/themes/Deadlight/progress-45.png /usr/share/plymouth/themes/Deadlight/progress-45.png
CopyFileTo /plymouth/themes/Deadlight/progress-47.png /usr/share/plymouth/themes/Deadlight/progress-47.png
CopyFileTo /plymouth/themes/Deadlight/progress-2.png /usr/share/plymouth/themes/Deadlight/progress-2.png
